# Statically link the C runtime on Windows so the .exe runs on any machine
# without needing Visual C++ Redistributable installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
